add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa00_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa10_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa20_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa30_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa01_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa11_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa21_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa31_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa02_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa12_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa22_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa32_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa03_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa13_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa23_reg[0] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[7] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[6] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[5] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[4] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[3] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[2] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[1] /Q}
add wave -position insertpoint {sim:/aes_cipher_top_tb/dut/\sa33_reg[0] /Q}
