onerror {resume}
quietly virtual signal -install /aes_cipher_top_tb/dut { (context /aes_cipher_top_tb/dut )&{sa00_reg_7_/Q , sa00_reg_6_/Q , sa00_reg_5_/Q , sa00_reg_4_/Q , sa00_reg_3_/Q , sa00_reg_2_/Q , sa00_reg_1_/Q , sa00_reg_0_/Q , sa10_reg_7_/Q , sa10_reg_6_/Q , sa10_reg_5_/Q , sa10_reg_4_/Q , sa10_reg_3_/Q , sa10_reg_2_/Q , sa10_reg_1_/Q , sa10_reg_0_/Q , sa20_reg_7_/Q , sa20_reg_6_/Q , sa20_reg_5_/Q , sa20_reg_4_/Q , sa20_reg_3_/Q , sa20_reg_2_/Q , sa20_reg_1_/Q , sa20_reg_0_/Q , sa30_reg_7_/Q , sa30_reg_6_/Q , sa30_reg_5_/Q , sa30_reg_4_/Q , sa30_reg_3_/Q , sa30_reg_2_/Q , sa30_reg_1_/Q , sa30_reg_0_/Q , sa01_reg_7_/Q , sa01_reg_6_/Q , sa01_reg_5_/Q , sa01_reg_4_/Q , sa01_reg_3_/Q , sa01_reg_2_/Q , sa01_reg_1_/Q , sa01_reg_0_/Q , sa11_reg_7_/Q , sa11_reg_6_/Q , sa11_reg_5_/Q , sa11_reg_4_/Q , sa11_reg_3_/Q , sa11_reg_2_/Q , sa11_reg_1_/Q , sa11_reg_0_/Q , sa21_reg_7_/Q , sa21_reg_6_/Q , sa21_reg_5_/Q , sa21_reg_4_/Q , sa21_reg_3_/Q , sa21_reg_2_/Q , sa21_reg_1_/Q , sa21_reg_0_/Q , sa31_reg_7_/Q , sa31_reg_6_/Q , sa31_reg_5_/Q , sa31_reg_4_/Q , sa31_reg_3_/Q , sa31_reg_2_/Q , sa31_reg_1_/Q , sa31_reg_0_/Q , sa02_reg_7_/Q , sa02_reg_6_/Q , sa02_reg_5_/Q , sa02_reg_4_/Q , sa02_reg_3_/Q , sa02_reg_2_/Q , sa02_reg_1_/Q , sa02_reg_0_/Q , sa12_reg_7_/Q , sa12_reg_6_/Q , sa12_reg_5_/Q , sa12_reg_4_/Q , sa12_reg_3_/Q , sa12_reg_2_/Q , sa12_reg_1_/Q , sa12_reg_0_/Q , sa22_reg_7_/Q , sa22_reg_6_/Q , sa22_reg_5_/Q , sa22_reg_4_/Q , sa22_reg_3_/Q , sa22_reg_2_/Q , sa22_reg_1_/Q , sa22_reg_0_/Q , sa32_reg_7_/Q , sa32_reg_6_/Q , sa32_reg_5_/Q , sa32_reg_4_/Q , sa32_reg_3_/Q , sa32_reg_2_/Q , sa32_reg_1_/Q , sa32_reg_0_/Q , sa03_reg_7_/Q , sa03_reg_6_/Q , sa03_reg_5_/Q , sa03_reg_4_/Q , sa03_reg_3_/Q , sa03_reg_2_/Q , sa03_reg_1_/Q , sa03_reg_0_/Q , sa13_reg_7_/Q , sa13_reg_6_/Q , sa13_reg_5_/Q , sa13_reg_4_/Q , sa13_reg_3_/Q , sa13_reg_2_/Q , sa13_reg_1_/Q , sa13_reg_0_/Q , sa23_reg_7_/Q , sa23_reg_6_/Q , sa23_reg_5_/Q , sa23_reg_4_/Q , sa23_reg_3_/Q , sa23_reg_2_/Q , sa23_reg_1_/Q , sa23_reg_0_/Q , sa33_reg_7_/Q , sa33_reg_6_/Q , sa33_reg_5_/Q , sa33_reg_4_/Q , sa33_reg_3_/Q , sa33_reg_2_/Q , sa33_reg_1_/Q , sa33_reg_0_/Q }} state_reg
quietly WaveActivateNextPane {} 0
add wave -noupdate /aes_cipher_top_tb/done
add wave -noupdate /aes_cipher_top_tb/text_out
add wave -noupdate /aes_cipher_top_tb/clk
add wave -noupdate /aes_cipher_top_tb/done
add wave -noupdate /aes_cipher_top_tb/text_out
add wave -noupdate /aes_cipher_top_tb/clk
add wave -noupdate /aes_cipher_top_tb/done
add wave -noupdate /aes_cipher_top_tb/text_out
add wave -noupdate /aes_cipher_top_tb/dut/ld
add wave -noupdate /aes_cipher_top_tb/clk
add wave -noupdate /aes_cipher_top_tb/dut/key
add wave -noupdate /aes_cipher_top_tb/dut/rst
add wave -noupdate -divider {state register}
add wave -noupdate /aes_cipher_top_tb/dut/state_reg
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa00_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa10_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa20_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa30_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa01_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa11_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa21_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa31_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa02_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa12_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa22_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa32_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa03_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa13_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa23_reg_0_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_7_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_6_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_5_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_4_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_3_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_2_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_1_/Q
add wave -noupdate /aes_cipher_top_tb/dut/sa33_reg_0_/Q
add wave -noupdate -divider text_in_reg
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {157062 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 371
configure wave -valuecolwidth 330
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {816958 ps}
