vcd file test.vcd
#vcd add -r /aes_cipher_top_tb/*
add wave sim:/aes_cipher_top_tb/*
add wave -radix hex { dcnt {
sim:/aes_cipher_top_tb/dut/dcnt_reg_3_/Q
sim:/aes_cipher_top_tb/dut/dcnt_reg_2_/Q
sim:/aes_cipher_top_tb/dut/dcnt_reg_1_/Q
sim:/aes_cipher_top_tb/dut/dcnt_reg_0_/Q
}}
# add aes_coprocessor signals
#run 639990ps
#if 0 {
add wave -radix hex { State_reg {
sim:/aes_cipher_top_tb/dut/sa00_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa00_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa10_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa20_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa30_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa01_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa11_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa21_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa31_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa02_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa12_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa22_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa32_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa03_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa13_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa23_reg_0_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_7_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_6_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_5_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_4_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_3_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_2_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_1_/Q
sim:/aes_cipher_top_tb/dut/sa33_reg_0_/Q

}}
#}
add wave -radix hex { plaintext {
sim:/aes_cipher_top_tb/dut/text_in_r_reg_127_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_126_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_125_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_124_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_123_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_122_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_121_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_120_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_119_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_118_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_117_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_116_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_115_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_114_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_113_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_112_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_111_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_110_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_109_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_108_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_107_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_106_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_105_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_104_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_103_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_102_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_101_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_100_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_99_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_98_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_97_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_96_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_95_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_94_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_93_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_92_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_91_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_90_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_89_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_88_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_87_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_86_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_85_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_84_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_83_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_82_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_81_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_80_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_79_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_78_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_77_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_76_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_75_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_74_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_73_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_72_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_71_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_70_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_69_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_68_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_67_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_66_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_65_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_64_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_63_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_62_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_61_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_60_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_59_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_58_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_57_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_56_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_55_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_54_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_53_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_52_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_51_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_50_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_49_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_48_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_47_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_46_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_45_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_44_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_43_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_42_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_41_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_40_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_39_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_38_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_37_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_36_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_35_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_34_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_33_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_32_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_31_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_30_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_29_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_28_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_27_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_26_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_25_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_24_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_23_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_22_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_21_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_20_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_19_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_18_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_17_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_16_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_15_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_14_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_13_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_12_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_11_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_10_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_9_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_8_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_7_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_6_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_5_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_4_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_3_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_2_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_1_/Q
sim:/aes_cipher_top_tb/dut/text_in_r_reg_0_/Q

}}

##run 639990ps
#run 1109316ps
run 1151982ps

